CREATE TABLE MCHNE_USERINFO (
    USERID bigint(20) NOT NULL AUTO_INCREMENT,
    USERNAME varchar(100) NOT NULL,
    FIRSTNAME varchar(50) NOT NULL,
    LASTNAME varchar(50) NOT NULL,
    EMAIL varchar(50) NOT NULL,
    PRIMARY KEY (USERID),
    UNIQUE KEY UK_username (USERNAME)
)